name: Vial Continuous Integration
run-name: ${{ github.actor }}
on: [push]
jobs:
    build:
        runs-on: [ubuntu-latest]
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
          - name: Install Bazelisk
            uses: bazelbuild/setup-bazelisk@v3
          - name: Mount bazel cache
            uses: actions/cache@v4
          - name: Build Repo
            run: bazel build //...:all
