name: Vial Continuous Integration
run-name: ${{ github.actor }}
on: [push]
jobs:
    build:
        runs-on: [ubuntu-latest]
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
          - name: Install Bazelisk
            uses: bazelbuild/setup-bazelisk@v3
          - name: Build Repo
            run: bazel build //...:all
          - name: Run Tests
            run: bazel test //...:all
          - name: Run clang-tidy
            uses: HorstBaerbel/action-clang-tidy@1.2